/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pharmacare.pharma.order.manager.view;

import com.pharmacare.pharma.order.manager.model.PharmacyOrder;
import javax.swing.JOptionPane;

/**
 *
 * @author hrojas
 */
public class OrderSummaryForm extends javax.swing.JFrame {

    private PharmacyOrder order;
    private PharmaOrderForm mainForm;
    
    /**
     * Creates new form OrderSummaryForm
     */
    public OrderSummaryForm() {
        initComponents();
    }

    public void setOrder(PharmacyOrder order) {
        this.order = order;
    }
    
    public void setMainForm(PharmaOrderForm mainForm) {
        this.mainForm = mainForm;
    }
    
    public void updateLabels() {
        if (order != null) {
            // Actualizar el título de la ventana con el distribuidor
            String distributor = order.getDistributor() != null ? order.getDistributor() : "Desconocido";
            setTitle("Pedido al distribuidor " + distributor);

            // Actualizar lblMedicineInfo
            String medicineInfo = String.format("%s unidades del %s %s",
                    order.getRequiredQuantity(),
                    order.getMedicineTypeName(),
                    order.getNameMedicine());
            lblMedicineInfo.setText(medicineInfo);

            // Actualizar lblAddressInfo
            lblAddressInfo.setText(order.getAddressInfo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMedicineInfo = new javax.swing.JLabel();
        lblAddressInfo = new javax.swing.JLabel();
        lblDescOrder = new javax.swing.JLabel();
        lblSendTo = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMedicineInfo.setText("jLabel1");

        lblAddressInfo.setText("jLabel1");

        lblDescOrder.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblDescOrder.setText("Descripcion pedido:");

        lblSendTo.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblSendTo.setText("Despachar a:");

        btnEnviar.setText("Enviar pedido");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar pedido");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescOrder)
                            .addComponent(lblMedicineInfo)
                            .addComponent(lblSendTo)
                            .addComponent(lblAddressInfo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnEnviar)
                        .addGap(60, 60, 60)
                        .addComponent(btnCancel)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblDescOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMedicineInfo)
                .addGap(18, 18, 18)
                .addComponent(lblSendTo)
                .addGap(18, 18, 18)
                .addComponent(lblAddressInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnCancel))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea cancelar el pedido?",
            "Confirmar cancelación",
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirm == JOptionPane.YES_OPTION) {
        
            lblMedicineInfo.setText("");
            lblAddressInfo.setText("");

            this.setVisible(false);

        
            if (mainForm != null) {
                mainForm.setComponentsEnabled(true);
                mainForm.setVisible(true);
                mainForm.requestFocus();
            }
        } 
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        String successMessage = "El pedido ha sido enviado satisfactoriamente.";
        JOptionPane.showMessageDialog(this, successMessage, "Pedido Enviado", JOptionPane.INFORMATION_MESSAGE);
        
        System.out.println(successMessage);
        lblMedicineInfo.setText("");
        lblAddressInfo.setText("");
        this.setVisible(false);
        
        if (mainForm != null) {
            mainForm.setComponentsEnabled(true);
            mainForm.cleanForm();            
            mainForm.setVisible(true);
            mainForm.requestFocus();
        }
        
    }//GEN-LAST:event_btnEnviarActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddressInfo;
    private javax.swing.JLabel lblDescOrder;
    private javax.swing.JLabel lblMedicineInfo;
    private javax.swing.JLabel lblSendTo;
    // End of variables declaration//GEN-END:variables
}
